export const dummy = {
  dates: { maximum: "2023-02-20", minimum: "2023-01-03" },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/b1Y8SUb12gPHCSSSNlbX4nB3IKy.jpg",
      genre_ids: [16, 12, 35, 10751, 14],
      id: 315162,
      original_language: "en",
      original_title: "Puss in Boots: The Last Wish",
      overview:
        "아홉 개의 목숨 중 단 하나의 목숨만 남은 장화신은 고양이.  마지막 남은 목숨을 지키기 위해 히어로의 삶 대신 반려묘의 삶을 선택한 그에게 찾아온 마지막 기회, 바로 소원을 들어주는 소원별이 있는 곳을 알려주는 지도!  잃어버린 목숨을 되찾고 다시 히어로가 되기를 꿈꾸는 장화신은 고양이는 뜻밖에 동료가 된 앙숙 파트너 '키티 말랑손', 그저 친구들과 함께라면 모든 게 행복한 강아지 '페로'와 함께 소원별을 찾기 위해 길을 떠난다.  그리고 소원별을 노리는 또 다른 빌런들과 마주치게 되는데…",
      popularity: 2887.698,
      poster_path: "/rKgvctIuPXyuqOzCQ16VGdnHxKx.jpg",
      release_date: "2023-01-04",
      title: "장화신은 고양이: 끝내주는 모험",
      video: false,
      vote_average: 8.5,
      vote_count: 3912,
    },
    {
      adult: false,
      backdrop_path: "/8YFL5QQVPy3AgrEQxNYVSgiPEbe.jpg",
      genre_ids: [12, 878, 35],
      id: 640146,
      original_language: "en",
      original_title: "Ant-Man and the Wasp: Quantumania",
      overview:
        "슈퍼히어로 파트너인 스캇 랭과 호프 반 다인, 호프의 부모 재닛 반 다인과 행크 핌, 그리고 스캇의 딸 캐시 랭까지 미지의 양자 영역 세계 속에 빠져버린 앤트맨 패밀리. 그 곳에서 새로운 존재들과 무한한 우주를 다스리는 정복자 캉을 만나며, 그 누구도 예상 못 한 모든 것의 한계를 뛰어넘는 모험을 시작하게 되는데…",
      popularity: 2152.901,
      poster_path: "/cw6jBnTauNmEEIIXcoNEyoQItG7.jpg",
      release_date: "2023-02-15",
      title: "앤트맨과 와스프: 퀀텀매니아",
      video: false,
      vote_average: 6.5,
      vote_count: 539,
    },

    {
      adult: false,
      backdrop_path: "/vXjpwkXPirBmgdEpIknfN8ziDD.jpg",
      genre_ids: [16, 12, 14, 35],
      id: 947938,
      original_language: "ru",
      original_title: "Мальчик-дельфин",
      overview:
        "돌고래야, 사람이야?! 정체를 알 수 없는 녀석이 온다! 바다 속 돌고래와 함께 자란 소년 ‘보이’ 어느 날 친엄마의 존재를 알게 된 ‘보이’는 자신의 뿌리를 궁금해하기 시작하고 … 혼란스러운 상황 속 ‘보이’는 악당 ‘옥토퍼스’로 인해 엄마 돌고래 ‘나나’를 잃고 해안가로 떠밀려간다. 평생을 자신이 돌고래인 줄 알고 살던 ‘보이’는 해안가에 사는 ‘머버리드 선장’의 도움으로 친엄마를 찾아내기로 결심하는데 … 2023년, 올겨울 유일무이 오션 어드벤처가 온다!",
      popularity: 525.541,
      poster_path: "/Aif2IsFGCur5KoXnjkXyAhishMj.jpg",
      release_date: "2023-01-25",
      title: "돌핀보이",
      video: false,
      vote_average: 6.1,
      vote_count: 29,
    },
    {
      adult: false,
      backdrop_path: "/gwRMwljwHoNCyyJVgMA2XC4qPUU.jpg",
      genre_ids: [18, 35],
      id: 615777,
      original_language: "en",
      original_title: "Babylon",
      overview:
        "황홀하면서도 위태로운 고대 도시 바빌론에 비유되는 할리우드에서 전성기를 누리고 있는 당대 최고의 스타 잭 콘래드.  누구나 잭과 같은 성공을 꿈꾸지만 아무나 이룰 수 없던 그 때, 화려한 데뷔를 위해 당차게 야망을 좇는 넬리 라로이와 열정적인 청년 매니 토레스가 영화 같은 삶을 꿈꾸며 할리우드에 입성한다. 하지만 할리우드에서는 기존 영화 산업의 틀을 깬 새로운 변화가 시작되고 그 격변의 한가운데에서 잭과 넬리, 그리고 매니는 살아남아 각자의 꿈을 이루기 위해 고군분투하는데...",
      popularity: 480.657,
      poster_path: "/5Wnt03vRoKphp1ADWgHKus20vLX.jpg",
      release_date: "2023-02-01",
      title: "바빌론",
      video: false,
      vote_average: 7.6,
      vote_count: 1111,
    },
    {
      adult: false,
      backdrop_path: "/vLPSvAt1CnfmDCeqG3zkFh0s6S4.jpg",
      genre_ids: [10752, 28],
      id: 542196,
      original_language: "en",
      original_title: "Wolf Hound",
      overview:
        "연합군의 전투비행단이 독일 전투기에 급습을 당한다. 홀로 적진에 추락한 파일럿은 독일군의 추격을 받고 런던 폭격의 일급 작전인 코드네임 ‘울프 하운드’를 알게 된다. 독일군 기지에 잠입해 포로로 잡힌 동료를 탈출시키고 폭격을 막기 위해 함께 지상전과 공중전을 벌이는데…",
      popularity: 470.333,
      poster_path: "/uSQq9TExOdZc5PCyxBuqaVuALZ7.jpg",
      release_date: "2023-02-09",
      title: "울프 하운드",
      video: false,
      vote_average: 6.7,
      vote_count: 72,
    },
    {
      adult: false,
      backdrop_path: "/rodjjIJ8oh9nuBp86PhojcYHTEN.jpg",
      genre_ids: [28, 9648, 53, 80],
      id: 740952,
      original_language: "en",
      original_title: "Savage Salvation",
      overview:
        "마약 중독을 이겨내고 새로운 삶을 살길 원하는 ‘존’(잭 휴스턴)과 ‘루비’(윌라 피츠제럴드). 둘은 결혼을 약속하고 루비의 형부 ‘피터'(존 말코비치)는 존을 가족으로 따뜻하게 맞아준다. 과거의 죄를 씻고 구원을 바라는 루비의 세례를 앞둔 날, 약물 과다 투여로 죽어 있는 루비를 발견한 존은 절망에 빠지고 그녀를 죽음에 이르게 한 마약 공급책을 끝장내기 위해 복수에 나선다. 마을의 ‘마이크’ 보안관(로버트 드 니로)은 존의 폭주를 막기 위해 뒤를 쫓는데...",
      popularity: 328.155,
      poster_path: "/lvaksAQd82i4fJqr16664GcGUTf.jpg",
      release_date: "2023-01-26",
      title: "새비지 맨",
      video: false,
      vote_average: 6.6,
      vote_count: 103,
    },
    {
      adult: false,
      backdrop_path: "/6YRQ8l93ZEs6x4rZojWoHIWdguK.jpg",
      genre_ids: [28, 80],
      id: 1024546,
      original_language: "en",
      original_title: "Detective Knight: Rogue",
      overview:
        "미국 전역에서 강도 사건이 발생하고 현장에 나간 동료 형사 ‘피츠제럴드’가 목숨을 잃는다. 전직 스포츠 선수들이 범인이라는 단서를 찾은 ‘나이트’는 그들의 배후에 불법 도박업자 ‘위나’가 있다는 사실을 알게 되고, 복수와 정의를 위해 그들의 본거지인 뉴욕으로 향한 ‘나이트’는 과연 정의를 사수하고 복수를 실현할 수 있을까",
      popularity: 282.939,
      poster_path: "/7TxWlHkz5Guc9DCYo7ruVvnskDk.jpg",
      release_date: "2023-02-09",
      title: "디텍티브 나이트: 가면의 밤",
      video: false,
      vote_average: 6.7,
      vote_count: 74,
    },
    {
      adult: false,
      backdrop_path: "/59U5B10vsmVbgcCXzsFrzfG6SRb.jpg",
      genre_ids: [35, 10751, 10402],
      id: 830784,
      original_language: "en",
      original_title: "Lyle, Lyle, Crocodile",
      overview:
        "쇼맨 헥터(하비에르 바르뎀)는 어느 날 노래하는 악어 라일(숀 멘데스)을 발견하게 되고, 돈과 명예를 얻게 될 성공적인 무대를 꿈꾼다. 그러나 무대공포증에 있던 라일로 인해 무대는 실패하고 헥터는 라일을 홀로 도심에 남기고 떠난다.​  한편, 뉴욕에 이사 온 프림 가족은 매일 밤 의문의 노랫소리로 신기한 경험을 하게 되고, 그 놀라운 정체와 마주하게 되면서 인생이 바뀌게 되는데…",
      popularity: 256.68,
      poster_path: "/aWr7F5vK8LIY31sqQgINobBjBBK.jpg",
      release_date: "2023-01-18",
      title: "라일 라일 크로커다일",
      video: false,
      vote_average: 7.6,
      vote_count: 345,
    },
    {
      adult: false,
      backdrop_path: "/vmDa8HijINCAFYKqsMz0YM3sVyE.jpg",
      genre_ids: [28, 80, 53],
      id: 747803,
      original_language: "en",
      original_title: "One Way",
      overview:
        "죽여라! 도망쳐라! 살고 싶다면! 돌아갈 수 없는 편도행 버스 안에서 벌어지는 숨막히는 긴장감!  마약 조직의 보스 '빅'의 돈과 마약을 훔쳐 달아난 '프레디'는 야간 버스에 탑승해 도망친다. '빅'의 눈을 피해 도망갈 곳을 찾는 '프레디'는 친구인 '제이제이'와 아버지에게 전화를 걸며 도망칠 방법을 찾는다. 한편, 버스 안에는 집을 가출한 '레이첼'이 함께 탑승해 '프레디'에게 관심을 가지는데... 버스에서 내릴 수 없다면 목숨을 걸고 도망가야 한다. 과연, '프레디'는 무사히 버스에서 내려 가족을 만날 수 있을까?",
      popularity: 147.206,
      poster_path: "/sIi1efc3FJvunsf4BoGgQ1ycB7S.jpg",
      release_date: "2023-02-09",
      title: "원 웨이",
      video: false,
      vote_average: 6.5,
      vote_count: 83,
    },
    {
      adult: false,
      backdrop_path: "/otOtC45BDzFW7nuxnWHMmnYsicK.jpg",
      genre_ids: [878, 27, 35],
      id: 536554,
      original_language: "en",
      original_title: "M3GAN",
      overview:
        "교통사고로 부모를 잃고 혼자가 된 소녀 ‘케이디’. 로봇 엔지니어이자, ‘케이디’의 보호자가 된 ‘젬마’는 ‘케이디’를 안전하게 지켜야 하는 프로그램이 입력된 AI 로봇 ‘메간’을 선물한다. 메간은 언제나 ‘케이디’의 곁을 지켜주며 함께 웃고, 힘들 땐 위로해주는 둘도 없는 친구가 된다. 어느 날, ‘케이디’가 위험에 처하자 ‘메간’은 예측할 수 없는 방향으로 업그레이드되며 감당할 수 없는 일들이 벌어지는데…",
      popularity: 1445.928,
      poster_path: "/v0TtgXaZZ6NeDxKackgQK9byEDL.jpg",
      release_date: "2023-01-25",
      title: "메간",
      video: false,
      vote_average: 7.5,
      vote_count: 1698,
    },
    {
      adult: false,
      backdrop_path: "/qAatLCuRhvLyNJbH5IGmxLyU3tx.jpg",
      genre_ids: [16, 14, 12],
      id: 876792,
      original_language: "ja",
      original_title: "劇場版 転生したらスライムだった件 紅蓮の絆編",
      overview:
        "[템페스트]의 서쪽에 위치한 [라자 소아국]. 한때는 금 채굴로 번영했지만 지금은 번영의 그림자는 찾아볼 수조차 없고, 호수는 광산의 독에 오염되어 나라는 위기 상황에 처했다. 여왕 '토와'는 왕가에 대대로 전해 오는 왕관의 마력을 사용해 독을 제거하며 백성을 지키고 있었지만, 그 대가로 왕관에 걸려 있던 저주가 온몸에 퍼져 수명이 단축되고 있었다. 그러던 중, 템페스트에 갑자기 나타난 오거의 생존자 '히이로'. 베니마루 일행의 형님뻘이었다는 히이로는, 토와의 도움으로 살아남았던 것이었다. 자신을 구해 준 토와와 [라자 소아국]을 지키기 위해, 템페스트의 리무루에게 도움을 청하기 위해 온 히이로는 베니마루와 운명의 재회를 한다. 라자를 위기에서 구하기 위해, 그리고 토와에게 걸린 저주의 수수께끼를 풀기 위해, 리무루는 라자로 향하는데...... 그곳에는 놀라운 음모가 기다리고 있었다!",
      popularity: 114.32,
      poster_path: "/kHeX34lOrTM793hCiCS72cIYY6i.jpg",
      release_date: "2023-02-02",
      title: "극장판 전생했더니 슬라임이었던 건에 대하여: 홍련의 인연편",
      video: false,
      vote_average: 7.4,
      vote_count: 37,
    },
    {
      adult: false,
      backdrop_path: "/zjpYDQlhvrAaohKRShu522sKJ87.jpg",
      genre_ids: [16, 35, 18],
      id: 783675,
      original_language: "ja",
      original_title: "THE FIRST SLAM DUNK",
      overview:
        "전국 제패를 꿈꾸는 북산고 농구부 5인방의 꿈과 열정, 멈추지 않는 도전을 그린 영화",
      popularity: 94.653,
      poster_path: "/coiJrdXAXuBkSGDvp9bZ7mkuU6E.jpg",
      release_date: "2023-01-04",
      title: "더 퍼스트 슬램덩크",
      video: false,
      vote_average: 8.3,
      vote_count: 12,
    },
    {
      adult: false,
      backdrop_path: "/fjgKMNFo6uj7znrWwTbLzNBVzIT.jpg",
      genre_ids: [27, 9648],
      id: 477462,
      original_language: "en",
      original_title: "The Twin",
      overview:
        "쌍둥이 아들을 잃은 레이첼 가족을 향해 위로를 가장한 이교 집단의 손길이 뻗친다.",
      popularity: 81.526,
      poster_path: "/obJRpZOfC4ul5dr7JIZHsvDyllf.jpg",
      release_date: "2023-02-08",
      title: "트윈",
      video: false,
      vote_average: 6,
      vote_count: 139,
    },
    {
      adult: false,
      backdrop_path: "/hhICjHximfBciqxX09d91GgghV8.jpg",
      genre_ids: [18],
      id: 965150,
      original_language: "en",
      original_title: "Aftersun",
      overview:
        "평범한 10대 소녀인 소피는 그동안 자신에게 소홀했던 아버지와 단둘이 튀르키예로 여행을 떠난다. 아버지와 처음으로 둘만의 오붓한 시간을 즐기는 동안, 소피는 어떻게든 자신을 즐겁게 해주려는 아버지의 새로운 이면을 보게 되는데…",
      popularity: 68.533,
      poster_path: "/zZh6x7aHtSxsIQCewZVKEykVNtO.jpg",
      release_date: "2023-02-01",
      title: "애프터썬",
      video: false,
      vote_average: 7.8,
      vote_count: 419,
    },
    {
      adult: false,
      backdrop_path: "/qp8qKiP7Q7zK4z3LItwWMHfV9kJ.jpg",
      genre_ids: [53],
      id: 764835,
      original_language: "en",
      original_title: "The Desperate Hour",
      overview:
        "긴급 경보 : 교내 총격 테러 발생  오전 8:00 에이미는 학교를 가기 싫어하는 아들을 뒤로 한 채 조깅을 나선다. 오전 8:59 아들의 학교에서 총격 테러가 발생했다. 오전 9:00 아들에게 연락이 닿지 않는다. 오전 9:36 아들이 유력한 용의자로 의심받고 있는 것을 알게 된다.  단 한 걸음도, 단 한 순간도 놓치지 못할 리얼 타임 서스펜스가 펼쳐진다!",
      popularity: 67.113,
      poster_path: "/nowGRB6389FFRoGEhq4wsu1GOit.jpg",
      release_date: "2023-01-04",
      title: "패닉 런",
      video: false,
      vote_average: 6.1,
      vote_count: 320,
    },
    {
      adult: false,
      backdrop_path: "/33qGtN2GpGEb94pn25PDPeWQZLk.jpg",
      genre_ids: [28],
      id: 894169,
      original_language: "en",
      original_title: "Vendetta",
      overview:
        "딸과 함께 평온한 일상을 보내고 있던 '윌리엄 던컨'.  그러나 의문의 범죄 집단에 의해 딸이 잔혹하게 살해되는 사건이 발생하고, 그녀를 죽인 범인 '대니'는 가벼운 형만을 선고받는다.  결국 자신의 손으로 직접 딸의 복수를 결심한 '던컨'은 '대니'를 살해하지만, 이는 그가 속한 범죄 집단과의 전면전을 알리는 계기가 되어 끝도 없는 전쟁의 서막이 열리는데...",
      popularity: 52.96,
      poster_path: "/uf3HYK3VdcXqH7wZVqQK58U0mO3.jpg",
      release_date: "2023-01-20",
      title: "벤데타: 복수의 시간",
      video: false,
      vote_average: 6.2,
      vote_count: 202,
    },
    {
      adult: false,
      backdrop_path: "/9VIURlZvfnmFACs2m0MdUDDC3In.jpg",
      genre_ids: [14, 18, 10749],
      id: 556694,
      original_language: "en",
      original_title: "Three Thousand Years of Longing",
      overview:
        "세상 모든 이야기에 통달한 서사학자 알리테아가 우연히 소원을 이뤄주는 정령 지니를 깨워낸다. 그녀에게 주어진 기회는 단 세 번. 마음속 가장 깊은 곳, 가장 오랫동안 바라온 소원을 말할 것!",
      popularity: 58.853,
      poster_path: "/hHmJGgb29sIxSK9EOf6d68mDnEM.jpg",
      release_date: "2023-01-04",
      title: "3000년의 기다림",
      video: false,
      vote_average: 7.1,
      vote_count: 660,
    },
    {
      adult: false,
      backdrop_path: "/70aVSo3fuZ94jyQ3rT64afEf8lV.jpg",
      genre_ids: [16, 12, 35, 10751, 14],
      id: 676710,
      original_language: "en",
      original_title: "The Amazing Maurice",
      overview:
        "신기한 능력으로 성공적인 사기 행각을 이어가던 모리스와 친구들! 4차원 소녀 ‘멜리시아’에게 정체가 탄로나 어쩔 수 없이 그녀를 도와 마을에 숨겨진 비밀을 찾아 나선 그들은 세상을 지배하려는 절대악 ‘쥐마왕’의 음모를 알아채지만 뜻하지 않은 위험에 처한다. 가까스로 잡혀있던 ‘복숭아’를 구해낸 모리스와 친구들은 마을에서 탈출을 시도하고, 멜리시아는 허당 피리꾼 ‘키이스’와 함께 쥐마왕에게 맞서기 위해 진짜 마술피리를 찾아나서는데..  쥐마왕의 정체는 과연 무엇? 그리고 모리스와 친구들은 무사히 마을에서 벗어날 수 있을 것인가?!",
      popularity: 24.805,
      poster_path: "/m4gi3r7JizAaURreUqjCk306vxz.jpg",
      release_date: "2023-02-15",
      title: "어메이징 모리스",
      video: false,
      vote_average: 6.3,
      vote_count: 29,
    },
    {
      adult: false,
      backdrop_path: "/dp4jcu2tlAyJnJNnCyHXnWnqhUl.jpg",
      genre_ids: [80, 18, 53],
      id: 889699,
      original_language: "fa",
      original_title: "عنکبوت مقدس",
      overview:
        "‘순교자의 땅’이라는 뜻을 가진 이란 최대의 종교도시, 마슈하드 그곳에서 1년 사이 16명의 여성을 살해한 연쇄 살인마 ‘거미’는 자신의 범행과 시체 유기 장소를 직접 언론에 제보하는 대담한 행동을 이어간다. 살인마의 행동에 정당성을 부여하는 여론이 일고 정부와 경찰마저 적극적으로 수사하지 않는 가운데 여성 저널리스트 ‘라히미’만이 홀로 살인마의 실체를 밝히기 위해 그의 뒤를 쫓는데…",
      popularity: 20.737,
      poster_path: "/bdaUrseeOHSaChDSaRypa11T3YZ.jpg",
      release_date: "2023-02-08",
      title: "성스러운 거미",
      video: false,
      vote_average: 7.4,
      vote_count: 106,
    },
    {
      adult: false,
      backdrop_path: "/1cnknzG8hDYq6qYk75HGzFTre4m.jpg",
      genre_ids: [80, 28],
      id: 606400,
      original_language: "ko",
      original_title: "교섭",
      overview:
        "분쟁지역 아프가니스탄에서 한국인들이 탈레반에게 납치되는 최악의 피랍사건이 발생한다. 교섭 전문이지만 아프가니스탄은 처음인 외교관 재호가 현지로 향하고, 국정원 요원 대식을 만난다. 원칙이 뚜렷한 외교관과 현지 사정에 능통한 국정원 요원. 입장도 방법도 다르지만,  사람은 인질을 살려야 한다는 목표를 향해 함께 나아간다. 살해 시한은 다가오고, 협상 상대, 조건 등이 시시각각 변하는 상황에서 교섭의 성공 가능성은 점점 희박해져 가는데...",
      popularity: 16.787,
      poster_path: "/qaVQoBuICpRq4i5Ke4Jm2ZngvxF.jpg",
      release_date: "2023-01-18",
      title: "교섭",
      video: false,
      vote_average: 5.3,
      vote_count: 3,
    },
  ],
  total_pages: 4,
  total_results: 64,
};
